### ISSUE TITLE
Funktionalität der Karte implementieren

### ISSUE THREAD

**Issue by maikfichtenkamm** [DhruvAggarwal01/ATdIT_Gruppe5#10]
1) eine geeignete Karte finden und im UI integrieren
2) Funktionalität "Reinzoomen" 
3) Menü anlegen
4) "Flags" anlegen: Markierungen auf der Karte die verlinkt sind zu bestimmenten Sachen z.B.
Standort Maschinen, Wegmarkierungen, wichtige Punkte markieren
5) Flags können andere Dokumente aufrufen
6) mehrere Tabs / mehrere Steinbrüche möglich

**Comment by DhruvAggarwal01** [comment]
bzw. Foto eines Steinbruchs nehmen statt Kartenfunktionalität mit Reinzoomen, etc.
