### ISSUE TITLE
MS Excel Datenbank anlegen/anpassen - Aufträge

### ISSUE THREAD

**Issue by SophieOrth** [DhruvAggarwal01/ATdIT_Gruppe5#30]
MS Excel Datenbank anlegen - die Aufträge speichert. 
Siehe Prototyp: Firma, Auftragsnummer, Steinart, Menge, Lieferdatum, Status, Abgeschlossen

**Comment by DhruvAggarwal01** [comment]
Der DB wie im ersten Comment von Sophie genannt mit den Spalten ergänzen und in "description" Spalte mock Daten einfügen
