### ISSUE TITLE
Clean Code (Modularisierung vom Code)

### ISSUE THREAD

**Issue by DhruvAggarwal01** [DhruvAggarwal01/ATdIT_Gruppe5#33]
lange Konstruktoren vermeiden, stattdessen mehrere Methoden, Subklassen verwenden, wenn möglich

**Comment by maikfichtenkamm** [comment]
und an Kommentare denken! und einheitliche Schreibweise sowie Sprache: Variablen- und Methodennamen in Englisch, aber Kommentare in Deutsch!
